### ISSUE TITLE
Do "error_messages" always have one entry?

### ISSUE THREAD

**Issue by MirzaMerdovic** [klarna/kco_rest_dotnet#10]
Hi,

This is a question more about the actual [Klarna API](https://developers.klarna.com/api/#errors) where it states that when error occurs API will send an error message object that contains a property: "error_messages" that may contain one or several error messages.
I tried several invalid request when creating the Order but I always have a json array with only one entry.
Example: 
```
"error_messages": [
    "Bad format: options.allowed_customer_types"
    ]

"error_messages" : [ 
    "Bad value: order_lines[0].total_tax_amount (may not be null), order_lines[0].tax_rate (may not be null)" 
]
```

Is there a scenario where I should expect several entries, or they will always be comma delimited? 

I also noticed that not all validation errors are going to occur in the response but only the first occurrence meaning if the property is simple it will be one error message and if the property is a complex object there might be several. I, of course, might be wrong about this, since I haven't exhausted all the cases.

Could someone please give me some clearance/guidelines regarding my inquiry.

Thanks,
Mirza.

**Comment by alexions** [comment]
Hi @MirzaMerdovic !

> I tried several invalid request when creating the Order

Did you try to integrate Checkout API or Payment API? I'm asking because you can create Order via both of them.

Thanks.

**Comment by MirzaMerdovic** [comment]
Hi @alexions, 
Sorry, I should've specified the path. I was trying Checkout API (POST ~/checkout/v3/orders)

**Comment by alexions** [comment]
Hi @MirzaMerdovic 

The KCO follows the "error contract". https://developers.klarna.com/api/#errors
It means that it is possible to have several errors entries. At the same time one message can contain several errors split by comma.

Unfortunately I cannot give you a real example when you get 2 messages, but you need to keep it in mind, that it is a possible case when you get >= 2 error entries.

Thanks.

**Comment by alexions** [comment]
Hi @MirzaMerdovic!

The KCO follows the "error contract": https://developers.klarna.com/api/#errors
It means that it is a possible situation when you get several error entries in the response.

The KCO sometimes combines errors using comma, but it's not a rule.

Unfortunately I cannot give you a real example how to get these errors, but you need to keep it in mind, that you still need to check all entries, but not only the first one.

Thanks!

**Comment by MirzaMerdovic** [comment]
Hi @alexions
Thanks for clarifying this!

I'll took the liberty to close this one  since it answers my question.
