### ISSUE TITLE
CustomerTokenDetails does not exponse card or bank details

### ISSUE THREAD

**Issue by mnording** [klarna/kco_rest_dotnet#15]
The object resulting in reading a customer token does not expose all data of the token from the api.
Api specs below: https://developers.klarna.com/api/#customer-token-api-read-customer-tokens-details

**Customer token model only exposes 2 properties**

        public string PaymentMethodType { get; set; }
        public string Status { get; set; }

> 

**Expected:**
I must be able to read out card data and bank data as returned by the API when reading the token details

**Comment by alexions** [comment]
Merged the fix

**Comment by alexions** [comment]
Available in v3.1.0
