### ISSUE TITLE
CreateCapture must return CaptureId

### ISSUE THREAD

**Issue by mnording** [klarna/kco_rest_dotnet#17]
Considering a merchant needs captureID when adding shipping-details on a capture, the SDK must return said capture ID if the creation of the capture is successful

**Comment by alexions** [comment]
The fix will be available in 3.1.0 version

**Comment by adamfinstorp** [comment]
This isn't fixed yet as far as I can tell (using 3.1.0). CreateCapture returns null since the response body from `POST /ordermanagement/v1/orders/{order_id}/captures` is empty. CaptureId should be extracted from the response header `Capture-Id`.

**Comment by freethan** [comment]
Indeed, re-opening and linking with #36. Thanks @adamfinstorp !

**Comment by alexions** [comment]
Fixed in the new release 3.1.2.
