### ISSUE TITLE
Allowed customer types error when updating order

### ISSUE THREAD

**Issue by eriksallberg** [klarna/kco_rest_dotnet#18]
When I try to update an order I get an error to the allowed_customer_types field even though I never set a value so it's still null. The error is a normal exception and not a ApiException.

Unexpected character encountered while parsing value: [. Path 'options.allowed_customer_types', line 67, position 32.

If I set for example "[\"person\", \"organization\"]" av value I get the following ApiException:
"Bad format: options.allowed_customer_types".

The bad request error comes when I create and update an order. 

I tried a lot of diffrent values but they all generate a bad request error.

Am I doing something wrong or is it a bug here? I feel it should default to "person" when the value is null.

**Comment by eriksallberg** [comment]
Tried with the example code for updating an order now and got the same error. Only change I made is running it async, so I use "await" instead of ".Result". 

var updatedOrder = await client.Checkout.UpdateOrder(order);

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/pull/28
