### ISSUE TITLE
GetPayoutsSummary uses wrong API endpoint

### ISSUE THREAD

**Issue by thoemy** [klarna/kco_rest_dotnet#19]
Calling GetPayoutsSummary makes a request to `https://api.klarna.com/settlements/v1/payouts` instead of `https://api.klarna.com/settlements/v1/payouts/summary`.

Line 38 in SettlementStore: https://github.com/klarna/kco_rest_dotnet/blob/7ed3a561ed4cbf1ec39105fd91789d6cf92c5c5e/Klarna.Rest/Klarna.Rest.Core/Store/SettlementStore.cs#L38

should probably replaced by
```chsarp
var url = ApiUrlHelper.GetApiUrlForController(ApiSession.ApiUrl, ApiControllerUri, "summary", nvm);
```

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/commit/ac9096cc2fa31501d9e3614427e4e1039b96dc53

Fixed.

**Comment by alexions** [comment]
The change will be available in the next release.

**Comment by alexions** [comment]
v3.1.0 released!
