### ISSUE TITLE
OrderLine says value 0 is null

### ISSUE THREAD

**Issue by HadrosR** [klarna/kco_rest_dotnet#21]
Getting a error when doing a Post checkout/v3/orders,

that one of my orderLines that has the value 0 on tax_rate and total_tax_amount
`Bad value: order_lines[3].tax_rate (may not be null), order_lines[3].total_tax_amount (may not be null)`

It did work fine to send 0 as tax_rate and total_tax_amount when sending with a request with all data as json. 

Is this intended?

**Comment by martingust** [comment]
I'm experiencing the same issue. 

**Message:** Error when calling POST https://api.playground.klarna.com/checkout/v3/orders.
**ErrorCode:** BAD_VALUE
**ErrorMessages:** "Bad value: order_lines[2].total_tax_amount (may not be null), order_lines[2].total_amount (may not be null), order_lines[1].total_tax_amount (may not be null), order_lines[2].unit_price (may not be null), order_lines[2].tax_rate (may not be null), order_lines[1].tax_rate (may not be null)"

**Comment by martingust** [comment]
The problem seemed to be with the Json Serializer Settings. I've created a pull request that fixes the issue.

**Comment by martingust** [comment]
A workaround to this is to create the Klarna Client with a custom JSON serializer as shown here https://github.com/klarna/kco_rest_dotnet/blob/v3.0/Klarna.Rest/Klarna.Rest.Core.Examples/CustomJsonSerializer.cs.

And in the custom serializer set:  `DefaultValueHandling = DefaultValueHandling.Include`

**Comment by alexions** [comment]
I merged change you offered. It's quite dangerous change, so it will go to a new 3.1.x version soon.

Thank you for contributing.

**Comment by ZodiacGemini** [comment]
When can we expect this to be implemented AKA v. 3.1 released?
