### ISSUE TITLE
Example request invalid: total_tax_value

### ISSUE THREAD

**Issue by johnknoop** [klarna/kco_rest_dotnet#24]
Hi

I'm using your example request for creating an order, but I get a validation error regarding the total tax amount:

![image](https://user-images.githubusercontent.com/3394270/51993044-6346bb00-24ae-11e9-982e-b3dc23639a95.png)

Any idea what might be wrong?

**Comment by alexions** [comment]
Hello @johnknoop 

I suppose it's an API example issue.

**So, by logic it should be:** 
The item tax is 10% for 5 items with price 10000 each.

```
(5*10000) * 10% = 5000  
50000 * 10% = 5000
```

**But in reality:**
The tax is included into the price and the formula should be like this:  
`total_amount - total_amount * 10000 / (10000 + tax_rate)`   
**10000** is just for precision

So change the item tax to **4545** and the order tax to **4545** and you will be able to create an order after that.

**Comment by alexions** [comment]
I already created a ticket for Klarna Checkout team to fix these examples.

**Comment by alexions** [comment]
@johnknoop can you confirm that this "fix" works for you?

**Comment by johnknoop** [comment]
Thanks a bunch @alexions , that helped! And I got to know Klarnas rules for tax calculations as well :)
