### ISSUE TITLE
RefundId is not returned from CreateRefund

### ISSUE THREAD

**Issue by adamfinstorp** [klarna/kco_rest_dotnet#36]
The id of the refund is not returned from the CreateRefund method (OrderManagementStore). It's available in the Refund-Id response header (POST /ordermanagement/v1/orders/{order_id}/refunds).

**Comment by freethan** [comment]
Good catch Adam, thanks for letting us know, a fix will land with the next release :)

**Comment by adamfinstorp** [comment]
Sounds great :)

**Comment by alexions** [comment]
Fixed in the new release 3.1.2.
