### ISSUE TITLE
Unsupported browser when making backend call to order

### ISSUE THREAD

**Issue by magnuskarlssonhm** [klarna/kco_rest_dotnet#39]
Hi,

I get the following response when trying the example code and going through step 3 at the documentation guide https://developers.klarna.com/documentation/klarna-checkout/integration-guide/render-the-checkout 

Do you have a working sample one can try with javascript and backend calls? Just want to change username and password and run the sample :)  

"Oops.
It seems you might be using an older web browser which is not safe nor compatible with modern web sites. For a smoother checkout experience, please install a newer browser.
Sorry for any inconvenience. For any questions, please contact customer service at Klarna.com.
**Which service do you use**
Example: Klarna Checkout, Klarna Payments, Order management, etc"

**To Reproduce**
` public KlarnaHelper()
        {
            client = new Klarna.Rest.Core.Klarna(username, password, KlarnaEnvironment.TestingEurope);
        }

        public string CreateCheckoutOrder()
        {
            var order = new CheckoutOrder
            {
                PurchaseCountry = "se",
                PurchaseCurrency = "sek",
                Locale = "sv-se",
                OrderAmount = 10000,
                OrderTaxAmount = 2000,

                MerchantUrls = new CheckoutMerchantUrls
                {
                    Terms = "https://www.estore.com/terms.html",
                    Checkout = "https://www.estore.com/checkout.html",
                    Confirmation = "https://www.estore.com/confirmation.html",
                    Push = "https://www.estore.com/push.html"
                },
                OrderLines = new List<OrderLine>()
                {
                    new OrderLine
                    {
                        Type = OrderLineType.physical,
                        Name = "Foo",
                        Quantity = 1,
                        UnitPrice = 10000,
                        TaxRate = 2500,
                        TotalAmount = 10000,
                        TotalTaxAmount = 2000,
                        TotalDiscountAmount = 0,
                    }
                },
                CheckoutOptions = new CheckoutOptions
                {
                    AllowSeparateShippingAddress = false,
                    ColorButton = "#FF9900",
                    ColorButtonText = "#FF9900",
                    ColorCheckbox = "#FF9900",
                    ColorCheckboxCheckmark = "#FF9900",
                    ColorHeader = "#FF9900",
                    ColorLink = "#FF9900",
                    DateOfBirthMandatory = false,
                    ShippingDetails = "bar",
                    AllowedCustomerTypes = new List<string>() { "person", "organization" }
                }
            };

            try
            {
                var createdOrder = client.Checkout.CreateOrder(order).Result;
                var orderId = createdOrder.OrderId;
                return GetOrder(orderId);
            }
            catch (ApiException ex)
            {
                Console.WriteLine(ex.ErrorMessage.ErrorCode);
                Console.WriteLine(ex.ErrorMessage.ErrorMessages);
                Console.WriteLine(ex.ErrorMessage.CorrelationId);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return "fail";
        }

        /// <summary>
        /// Retrieves a checkout order
        /// </summary>
        public string GetOrder(string orderId)
        {
            try
            {
                var order = client.Checkout.GetOrder(orderId).Result;
                return order.HtmlSnippet.ToString();
                Console.WriteLine(order.OrderId);
            }

            catch (ApiException ex)
            {
                Console.WriteLine(ex.ErrorMessage.ErrorCode);
                Console.WriteLine(ex.ErrorMessage.ErrorMessages);
                Console.WriteLine(ex.ErrorMessage.CorrelationId);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return "";
        }`

**Additional context**
Klarna.Rest.Core 3.1.1
VS 2017 template site for ASPNET Core MVC.

**Comment by alexions** [comment]
HI @magnuskarlssonhm 

Unfortunately, we have no ready-to-use web app. The .NET world has huge amount of different systems/templates/etc. The SDK can be embedded into any of them.

If we talk about the [ASP.NET Core Web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-2.2) you should do something like this:
https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-2.2
```
// GET: api/checkout
[HttpGet]
public JsonResult Get()
{
    // SDK: Do a Klarna Create checkout call
    ...
    var createdOrder = client.Checkout.CreateOrder(order).Result;
    return Json(createOrder);
}
```

So you will get the json reply when requesting the "api/checkout" endpoint (don't forget about the CORS policies)

And now - the frontend. The code from the [page](https://developers.klarna.com/documentation/klarna-checkout/integration-guide/render-the-checkout/#3-render-the-snippet-in-your-checkout-page) you mentioned is not perfect... 

If has some function, like "getSnippet" and "renderSnippet" with no code provided. As an example, I created the front-end code that you play with:

```
<html>
    <head>
        <title>KCO Example</title>
    </head>
    <body>
        <div id="my-checkout"></div>
        <script type="text/javascript">
        fetch('http://localhost:8080/api/checkout')
            .then(res => res.json())
            .then((out) => {
                var checkoutContainer = document.getElementById('my-checkout')
                checkoutContainer.innerHTML = out.htmlSnippet
                var scriptsTags = checkoutContainer.getElementsByTagName('script')
                // This is necessary otherwise the scripts tags are not going to be evaluated
                for (var i = 0; i < scriptsTags.length; i++) {
                    var parentNode = scriptsTags[i].parentNode
                    var newScriptTag = document.createElement('script')
                    newScriptTag.type = 'text/javascript'
                    newScriptTag.text = scriptsTags[i].text
                    parentNode.removeChild(scriptsTags[i])
                    parentNode.appendChild(newScriptTag)
                }
        }).catch(err => console.error(err));
        </script>
    </body>
</html>
```

In my example I used `localhost:8080` as a backend URL and be careful with `fetch` function. This is HTML5 and not all browsers support this.

But it works well. So my backed returned the JSON response, Frontend parsed this and executed all the scripts.

I hope this help you to build a nice Klarna Checkout!
Ping me if you still have any questions!

**Comment by alexions** [comment]
<img width="1407" alt="kco" src="https://user-images.githubusercontent.com/954028/58792416-671d5200-85f4-11e9-8c75-b10f9ed694e0.png">

**Comment by alexions** [comment]
Hi @magnuskarlssonhm 

Do you have any result? Does the provided code work for you?

**Comment by magnuskarlssonhm** [comment]
Hi @alexions, I needed to move on with this so we are currently evaluating an other product. Thanks anyway.

**Comment by alexions** [comment]
I will close the issue for now. 

BTW: Now we have 2 fully working examples for the WebApp and WebForms: https://github.com/klarna/kco_rest_dotnet/tree/v3.x/Klarna.Rest/SampleProjects

**Comment by DennisCG** [comment]
If it's OK to answer a closed issue, this worked for me.  In case it helps someone else. Fetch did not want to work for me.

```
    <script type="text/javascript">
        $.get("https://localhost:44378/api/checkout", function (data) {
            $(".result").html(data);
        });
    </script>
<div class="result"></div>
```
And in the controller. I put the code for CreateExample in a separate class and it returns the HTML snippet.
```
[HttpGet("checkout")]
        public ActionResult<string> checkout()
        {
            var createOrder = Methods.CreateExample();

            return createOrder;

        }
```
