### ISSUE TITLE
Update the status of a customer token

### ISSUE THREAD

**Issue by adamfinstorp** [klarna/kco_rest_dotnet#45]
I would like to be able to set the status of a customer token to "CANCELLED". Documentation can be found here: https://developers.klarna.com/api/#customer-token-api-update-the-status-of-a-customer-token

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/pull/47

**Comment by alexions** [comment]
Fixed in [v3.1.3](https://github.com/klarna/kco_rest_dotnet/releases/tag/v3.1.3)
