### ISSUE TITLE
Examples doesn't work

### ISSUE THREAD

**Issue by rafalwasniewski** [klarna/kco_rest_dotnet#5]
when i try to run examples on my MerchantId and SharedSecret it returns http error 401

**Comment by olaeld** [comment]
I also had this experience

**Comment by omelhus** [comment]
You'll need to create a test account and get API credentials from the CheckOut v3 site.

Check out https://developer.klarna.com/en/gb/kco-v3/test-credentials

**Comment by alexions** [comment]
Thanks @omelhus.
Yes, in order to use the SDK you need to have your own test credentials.
We changed the page, so please follow: https://developers.klarna.com/documentation/test-credentials
