### ISSUE TITLE
Typo in endpoint for "Release remaining authorization"

### ISSUE THREAD

**Issue by okebai** [klarna/kco_rest_dotnet#56]
**Describe the bug**
Therese a typo in the endpoint for `Klarna.Rest.Core.Klarna.OrderManagement.ReleaseRemainingAuthorization`, causing it to always return HTTP 404. Theres an underscore where there should be a dash.
https://github.com/klarna/kco_rest_dotnet/blob/32021ce2a6287a55cfd4843f0ebe6055a0f40525/Klarna.Rest/Klarna.Rest.Core/Store/OrderManagementStore.cs#L28

**Which service do you use**
Order management

**To Reproduce**
1. Call `Klarna.Rest.Core.Klarna.OrderManagement.ReleaseRemainingAuthorization`
2. 404 response.

**Expected behavior**
200 or 403 response.

**Comment by alexions** [comment]
The PR is ready to merge. Feel free to check it out and leave a comment.

**Comment by alexions** [comment]
Fixed in https://www.nuget.org/packages/Klarna.Rest.Core/3.1.4
