### ISSUE TITLE
Developer branch for pull requests

### ISSUE THREAD

**Issue by omelhus** [klarna/kco_rest_dotnet#6]
Please create a dev branch so that we can contribute to the library.

**Comment by alexions** [comment]
Hi @omelhus 

Sorry for such a long time to reply to you. Feel free to use the major branch (at the moment v3.x) to do any PRs. 

The golden rule is - keep the backward compatibility. If by some reasons your changes break it or you proposed a new SDK concept with the new architecture, still - create a PR to the major branch and then we will discuss how to address it (create a new branch, create a separate repo for the new concept, etc).

Thanks!
