### ISSUE TITLE
Issue installing the Klarna nuget package

### ISSUE THREAD

**Issue by BarrelMakerITSystems** [klarna/kco_rest_dotnet#63]
When I try to install the NuGet package, it fails, here is the command I use to attempt the install:
                Install-Package Klarna.Rest.Core -Version 3.1.4
 
Here is the output from the install command:
 
Attempting to gather dependency information for package 'Klarna.Rest.Core.3.1.4' with respect to project 'clogau.co.uk', targeting '.NETFramework,Version=v4.6'
Gathering dependency information took 506.91 ms
Attempting to resolve dependencies for package 'Klarna.Rest.Core.3.1.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Klarna.Rest.Core.3.1.4'
Resolved actions to install package 'Klarna.Rest.Core.3.1.4'
Retrieving package 'Klarna.Rest.Core 3.1.4' from 'nuget.org'.
Install failed. Rolling back...
Package 'Klarna.Rest.Core.3.1.4' does not exist in project 'clogau.co.uk'
Package 'Klarna.Rest.Core.3.1.4' does not exist in folder 'D:\projects\packages'
Executing nuget actions took 1.9 sec
Install-Package : Could not install package 'Klarna.Rest.Core 3.1.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package Klarna.Rest.Core -Version 3.1.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
Time Elapsed: 00:00:02.4569807

Planning to use the payments service but not getting that far.

In a .Net project add the NuGet packing using the following command:
                    Install-Package Klarna.Rest.Core -Version 3.1.4

I expect the package to install

Running .NET framework 4.6 using Visual Studio Pro 2017 (V 15.4.1)
I have tried installing various versions of the package including 3.1.3 and 3.1.2

**Comment by igeligel** [comment]
Hey @BarrelMakerITSystems 

> but the package does not contain any assembly references or content files that are compatible with that framework

It seems that the .NET version of your project needs to be updated to at least 4.6.1. We publish this package here as .NET Standard 2.0 package which means that .NET Framework versions 4.6.1 and newer are supported even though 4.7.2 is recommended.

> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. While NuGet considers .NET Framework 4.6.1 as supporting .NET Standard 1.5 through 2.0, there are several issues with consuming .NET Standard libraries that were built for those versions from .NET Framework 4.6.1 projects. For .NET Framework projects that need to use such libraries, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.

Source: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I recommend upgrading your local version to .NET 4.7.2. In most cases, this should work seamlessly.
