### ISSUE TITLE
Typo in SettlementsGetAllPayoutsResponse.cs "Paginatinon"

### ISSUE THREAD

**Issue by ckoenig95** [klarna/kco_rest_dotnet#64]
Inside the class [SettlementsGetAllPayoutsResponse](https://github.com/klarna/kco_rest_dotnet/blob/382ee63701c7628e00afd32e0dc5a03a3b45cc74/Klarna.Rest/Klarna.Rest.Core/Model/SettlementsGetAllPayoutsResponse.cs) the property holding the pagination information is called Paginati**n**on.

It should probably be called Pagination without the additional **n**.

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/pull/65

**Comment by alexions** [comment]
Merged. Will be available in the next release (after 3.1.4)
