### ISSUE TITLE
Merchant requested object is missing

### ISSUE THREAD

**Issue by marisks** [klarna/kco_rest_dotnet#8]
REST Api documentation describes Merchant Requested object:
https://developers.klarna.com/api/#checkout-api__order__merchant_requested

But it is not returned by the .NET Rest library.

Here is a related issue https://github.com/Geta/Klarna/issues/39

**Comment by mbooh** [comment]
Pull request for this is created.
https://github.com/klarna/kco_rest_dotnet/pull/9

**Comment by alexions** [comment]
Thank you for the PR! But i found this field: https://github.com/klarna/kco_rest_dotnet/blob/v3.0/Klarna.Rest/Klarna.Rest.Core/Model/CheckoutOrder.cs#L162

Unfortunately, the JsonProperty has a typo in the name. I will fix this typo in the next minor release.

**Comment by alexions** [comment]
https://github.com/klarna/kco_rest_dotnet/commit/0ce6ad56dacf392e9522306379e1c1d1b3c0ffb4

**Comment by alexions** [comment]
Available in v3.1.0
