### ISSUE TITLE
Klarna examples using deprecated code

### ISSUE THREAD

**Issue by LucGosso** [klarna/kco_rest_dotnet#96]
Could you please update the examples to use Order from Checkout namespace
client.Checkout.CreateOrder is deprecated. What to use? =)

Where do I find the newer API? in version 3.1.10

Where can i find a changelog? 

Im trying to go from 3.1.2 to 3.1.10

thx

**Comment by LucGosso** [comment]
New model Klarna.Rest.Core.Model.Checkout.Order is using CheckoutMerchantUrls which is Deprecated. But MerchantUrls is not used. Very confusing... Is there no conversion?

        [JsonProperty(PropertyName = "merchant_urls")]
        public CheckoutMerchantUrls MerchantUrls { get; set; }

**Comment by LucGosso** [comment]
Trying to use the captureobject, why does Klarna.Rest.Core.Model.OrderManagement.Order OrderLines not using same orderline object as CaptureObject.OrderLines ? #confused

Does it exists any conversions? 

        public async Task Capture(Klarna.Rest.Core.Model.OrderManagement.Order order)
        {
            await Klarna.OrderManagement.CreateCapture(order.OrderId, new CaptureObject()
            {
                CapturedAmount = order.OrderAmount,
                Description = "name of store",
                OrderLines = order.OrderLines
            });
        }

**Comment by freethan** [comment]
Hi there @LucGosso and thank you for raising these issues. In our effort to maintain backwards compatibility with older models we've inadvertently caused some trouble.

There is an ongoing effort to fix this here https://github.com/klarna/kco_rest_dotnet/pull/94.
We hope to get the examples updated in the same go. However due to limited availability, we cannot guarantee a delivery date.

A changelog relating to each release can be found here: https://github.com/klarna/kco_rest_dotnet/blob/v3.x/CHANGELOG.md

**Comment by LucGosso** [comment]
thx, seems to me we should go to version 3.1.9 meanwhile. is that a good option @freethan ?

IMHO dont be afraid of bumping a version and introduce breaking changes. looks messy when new api extends old.

**Comment by freethan** [comment]
Hi again @LucGosso . Yes indeed, I would propose to stay clear from 3.1.10 for now if this is causing troubles for you and wait for a bug fix release, or even better a breaking change version coming out later.

Thanks for the good feedback, we appreciate it 👍

**Comment by freethan** [comment]
Closing this issue. The plan is to release a `v3.1.12` as the final 3.x release without any attempts to maintain compatibility.

**Comment by LucGosso** [comment]
Good decision, if it is breaking, it should be v4. https://semver.org/
